
global:
  scrape_interval:     15s # Par défaut prometheus va scrapper les cibles toutes les 15 secondes

  # Attach these labels to any time series or alerts when communicating with
  # external systems (federation, remote storage, Alertmanager).
  external_labels:
    env: 'infrastructure'   # C'est simplement le nom de votre environnement

# spécification du serveur alertmanager # on sen fiche, vu avec Ethan
# alerting:
#   alertmanagers:
#   - static_configs:
#     - targets:
#       - localhost:9093
#     scheme: http
#     timeout: 10s

# fichier de règles pour l'alerting, c'est dans ce fichier que sont les définitions des alertes
# rule_files:
#   - "/alertmanager/alert.rules/alerts.rules.yml"

# la scrape configuration de prometheus, les hosts qu'il va contacter pour chercher les métrique
scrape_configs:

  - job_name: 'localhost'     # on peut mettre un nom de "scrap job" plus explicite
    static_configs:           # liste des cibles a scrap
      - targets: ['127.0.0.1:9100']
    scrape_interval: 5s       # frequence de scrap

### configuration de blackbox, notre probe http 
  - job_name: 'blackbox'
    metrics_path: /probe  # chemin d'acces aux metriques de blackbox
    params:
      module: [http_2xx]  # Look for a HTTP 200 response. (c'est un parametre a inclure dans la requete de scrap)
    relabel_configs:
    # La section relabel_configs est utilisée pour appliquer des
    # transformations sur les étiquettes (labels) des scrap target
    # avant que les métriques ne soient collectées.
      - source_labels: [__address__]
        regex: ([^,]*),(.*)           # regex pour tagger nos urls avec une virgule
        replacement: $1
        target_label: __param_target
      - source_labels: [__address__]
        target_label: instance
      - target_label: __address__
        replacement: localhost:9115   # The blackbox exporter's real hostname:port.

    static_configs:
      - targets: 
        - http://localhost:9090,prometheus
